#!/bin/bash
set -e

echo "[system] Building DKMS modules"
arch=$(uname --machine)
configs=(/usr/src/**/dkms.conf)
i=0
while [ $i -lt ${#configs[@]} ]; do
  i=$((i + 1))
  conf=${configs[$i]}
  dirname="$(basename "$(dirname "$conf")")"
  ver="$(echo "$dirname" | rev | cut -d'-' -f1 | rev)"
  name="$(echo "$dirname" | rev | cut -d'-' -f2- | rev)"
  echo "[dkms] ($i/${#configs[@]}) building $name"
  for modulesdir in /usr/lib/modules/*/; do
    kernel="$(basename "$modulesdir")/$arch"
    chronic dkms build -m "$name" -v "$ver" -k "$kernel"
    chronic dkms install --force -m "$name" -v "$ver" -k "$kernel"
  done
done

echo "[system] Populating /etc/system/commandline"
echo "${KARGS}" >/etc/system/commandline

echo "[system] Building initramfs"
find /usr/lib/modules -name vmlinuz | while read -r vmlinuz; do
  ln -s "$vmlinuz" /boot/vmlinuz-linux-zen
  chronic mkinitcpio -P
  rm /boot/vmlinuz-linux-zen
done
find /usr/lib/modules -maxdepth 1 -mindepth 1 -type d | while read -r dir; do
  mv /boot/initramfs-linux-zen.img "$dir/initramfs.img"
  break
done
