#!/bin/bash
set -e
UUID="${1:-$(date +"%Y-%m-%d-%H-%M-%S-00")}"
echo "[system] Creating live bootloader"

touch "/etc/system/archiso/${UUID}.uuid"
truncate -s 256MB /etc/system/efiboot.img
chronic mkfs.vfat -n EFI /etc/system/efiboot.img
chronic mmd -i /etc/system/efiboot.img EFI EFI/boot EFI/systemd EFI/CLOVER

chronic mcopy -i /etc/system/efiboot.img \
  /usr/lib/systemd/boot/efi/systemd-bootx64.efi ::EFI/boot/BOOTX64.EFI
chronic mcopy -i /etc/system/efiboot.img \
  /usr/lib/systemd/boot/efi/systemd-bootx64.efi ::EFI/systemd/systemd-bootx64.efi

mkdir -p /tmp/clover-loader
cp -a /etc/system/archiso/loader/. /tmp/clover-loader/
sed -i "s/%UUID%/${UUID}/g" \
  /tmp/clover-loader/entries/01-archiso-x86_64-linux.conf
chronic mcopy -s -i /etc/system/efiboot.img /tmp/clover-loader ::loader
rm -rf /tmp/clover-loader

mkdir -p /tmp/clover-esp/arkes/x86_64
cp -a /usr/lib/modules/*/vmlinuz /tmp/clover-esp/arkes/x86_64/vmlinuz
cp -a /usr/lib/modules/*/initramfs.img /tmp/clover-esp/arkes/x86_64/initramfs.img
chronic mcopy -s -i /etc/system/efiboot.img /tmp/clover-esp/arkes ::arkes
rm -rf /tmp/clover-esp

chronic mcopy -s -i /etc/system/efiboot.img \
  /etc/system/clover/CLOVER/. ::EFI/CLOVER/
chronic mcopy -o -i /etc/system/efiboot.img \
  /etc/system/clover-config.plist ::EFI/CLOVER/config.plist

mkdir -p /etc/system/archiso/{boot/grub,EFI/CLOVER,arkes/x86_64}

cp /etc/system/clover/cdboot /etc/system/archiso/boot/grub/eltorito.img
cp -a /etc/system/clover/CLOVER/. /etc/system/archiso/EFI/CLOVER/
mkdir -p /etc/system/archiso/EFI/systemd
cp -a /usr/lib/systemd/boot/efi/systemd-bootx64.efi \
  /etc/system/archiso/EFI/systemd/

cp -a /usr/lib/modules/*/vmlinuz /etc/system/archiso/arkes/x86_64
cp -a /usr/lib/modules/*/initramfs.img /etc/system/archiso/arkes/x86_64
cp -a /usr/share/edk2-shell/x64/Shell.efi /etc/system/archiso/shellx64.efi
cp -ar /boot/memtest86+ /etc/system/archiso
