#!/bin/bash
set -e
echo "[system] Hostname: $HOSTNAME"
echo "[system] Timezone: $TIMEZONE"
echo "[system] Keymap: $KEYMAP"
echo "[system] Font: $FONT"
echo "[system] Language: $LANGUAGE"
echo "[system] Encoding: $ENCODING"
echo "${HOSTNAME:-arkes}" >/etc/hostname
chmod a+r /etc/hostname
ln -sf "/usr/share/zoneinfo/${TIMEZONE:-UTC}" /etc/localtime
echo "KEYMAP=${KEYMAP:-us}" >/etc/vconsole.conf
echo "FONT=${FONT:-ter-124n}" >>/etc/vconsole.conf
echo "LANG=${LANGUAGE:-en_US}.${ENCODING:-UTF-8}" >/etc/locale.conf
language="${LANGUAGE:-en_US}"
encoding="${ENCODING:-UTF-8}"
if [[ "${language}.${encoding}" != "en_US.UTF-8" ]]; then
  echo "${language}.${encoding} ${encoding}" >>/etc/locale.gen
fi
echo "[system] Generating locale"
chronic locale-gen
echo "[system] Removing unused locales"
cat >/etc/locale.nopurge <<'EOF'
MANDELETE
SHOWFREEDSPACE
VERBOSE
NOCOLOR
${language}.${encoding}
EOF
if [[ "${language}.${encoding}" != "en_US.UTF-8" ]]; then
  echo "en_US.UTF-8" >>/etc/locale.nopurge
fi
chronic localepurge
rm /etc/locale.nopurge
echo "[system] Ranking mirrorlist"
rankmirrors /etc/pacman.d/mirrorlist | tail -n +2 >/etc/pacman.d/mirrorlist.new
rm /etc/pacman.d/mirrorlist
mv /etc/pacman.d/mirrorlist.new /etc/pacman.d/mirrorlist
/usr/lib/system/initialize_pacman
