[lint]
extend-select = [
    "UP",
    "PL",
    "ANN",
    "S",
]
ignore = [
    "ANN001",
    "ANN003",
    "ANN401",
    "B009",
    "B010",
    "BLE001",
    "DTZ005",
    "DTZ007",
    "FLY002",
    "FURB188",
    "N999",
    "PLR0911",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PLR2004",
    "PLR6301",
    "PLW0603",
    "RUF015",
    "S101",
    "S404",
    "S603",
    "S607",
    "TRY002",
    "E402"
]
