# syntax = docker/dockerfile:1.7

FROM golang:1.26.1-alpine3.23 as dockerfile2llbjson

WORKDIR /app
COPY tools/dockerfile2llbjson/go.mod tools/dockerfile2llbjson/go.sum ./
RUN go mod download
COPY tools/dockerfile2llbjson/main.go ./
RUN CGO_ENABLED=0 go build -o /app/dockerfile2llbjson .
RUN apk add jq
ARG \
    _IMAGE=alpine@sha256:4b7ce07002c69e8f3d704a9c5d6fd3053be500b7f1c69fc0d80990c2ad8dd412 \
    _LLB='[{"Op":{"source":{"identifier":"docker-image://docker.io/library/alpine@sha256:4b7ce07002c69e8f3d704a9c5d6fd3053be500b7f1c69fc0d80990c2ad8dd412"}},"platform":{"Architecture":"amd64","OS":"linux"},"constraints":{}},{"inputs":[{"digest":"sha256:d7da300b78ded70bf3032141b65155e613989c41dae86af433196b6a8ab4c45b"}],"Op":{}}]'
RUN data="$(echo "FROM ${_IMAGE}" | /app/dockerfile2llbjson)" \
    && echo "$data" \
    && diff -U3 <(echo "${_LLB}" | jq) <(echo "$data" | jq) \
    && echo "Test passed"

FROM ubuntu:25.04

COPY --from=dockerfile2llbjson /app/dockerfile2llbjson /usr/bin/dockerfile2llbjson

# Avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYENV_ROOT=/opt/pyenv \
    PATH=/opt/pyenv/shims:/opt/pyenv/bin:$PATH

# Install core tools + build deps for pyenv + your system deps
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    containernetworking-plugins \
    fuse-overlayfs \
    gh \
    gnupg \
    golang-go \
    jq \
    libcairo2-dev \
    libdbus-1-dev \
    libgirepository-2.0-dev \
    libglib2.0-dev \
    libpython3-dev \
    meson \
    netavark \
    ninja-build \
    ostree \
    pkg-config \
    podman \
    python3-dev \
    skopeo \
    sudo \
    uidmap \
    xdelta3 \
    zstd \
    # Pyenv extra dependencies
    curl \
    gir1.2-gtk-4.0 \
    git \
    libbz2-dev \
    libffi-dev \
    liblzma-dev \
    libncursesw5-dev \
    libreadline-dev \
    libsqlite3-dev \
    libssl-dev \
    libxml2-dev \
    libxmlsec1-dev \
    tk-dev \
    xz-utils \
    zlib1g-dev \
    # Install docker-ce
    && install -m 0755 -d /etc/apt/keyrings \
    && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | tee /etc/apt/keyrings/docker.asc > /dev/null \
    && chmod a+r /etc/apt/keyrings/docker.asc \
    && echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    docker-ce-cli \
    # Install python 3.13
    && curl https://pyenv.run | bash \
    && pyenv install 3.13 \
    && pyenv global 3.13 \
    && pyenv exec python -m pip install --root-user-action ignore --upgrade pip \
    && pyenv exec python -m pip install --root-user-action ignore --upgrade \
    requests \
    setuptools \
    wheel \
    && pyenv exec python -m pip install --root-user-action ignore --upgrade \
    dbus-python \
    podman \
    progressbar2 \
    PyGObject \
    pyxattr \
    # Cleanup
    && pip cache purge \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf \
    /var/lib/apt/lists/* \
    /tmp/* \
    /var/tmp/*

RUN mkdir /github \
    && usermod --login runner "$(id -nu 1000)" \
    && echo 'runner:runner' | chpasswd \
    && usermod -aG sudo runner \
    && printf 'runner ALL=(ALL) NOPASSWD: ALL\nDefaults:runner env_keep += "PATH PYENV_ROOT", secure_path = "%s"\n' "$PATH" > /etc/sudoers.d/runner \
    && mkdir -p \
    /github/{workspace,workflow,home} \
    /etc/containers \
    /tmp/podman-run \
    /var/lib/containers/storage \
    /var/cache/podman \
    /var/cache/pacman \
    /var/lib/pacman \
    /etc/pacman.d/gnupg \
    && ln -s /usr/bin/false /usr/local/bin/systemd-detect-virt

COPY overlay/base/etc/containers/registries.conf.d/10-docker.conf /etc/containers/registries.conf.d/10-docker.conf
COPY overlay/base/usr/share/containers/storage.conf /usr/share/containers/storage.conf

RUN sed -i '/^#mount_program/ s|# *||' /usr/share/containers/storage.conf

USER 0
