#!/bin/bash
set -e
echo "[system] Cleaning up kernel build artifacts"

find /usr/lib/modules -maxdepth 1 -mindepth 1 -type d | while read -r dir; do
  rm -f "$dir/initramfs.img"
  rm -rf build/
done
find /boot -mindepth 1 -type f -print0 | xargs -r0 rm
find /boot -mindepth 1 -type d -print0 | xargs -r0 rmdir
