HoldPkg = pacman glibc
#XferCommand = /usr/bin/wget --retry-on-http-error=429 --waitretry=20 --passive-ftp -c -O %o %u
XferCommand = /usr/bin/curl --retry 5 --retry-delay 0 --retry-max-time 40 -# -L -C - -f -o %o %u
NoExtract = /etc/pacman.conf /etc/resolv.conf /etc/motd /etc/sudoers /etc/pacman.d/mirrorlist /usr/lib/initcpio/install/fsck /usr/share/containers/storage.conf
ILoveCandy
