#!/bin/bash
set -euo pipefail

path="$(realpath "${1:-/}")"
ref_exact=$(mktemp)
ref_before=$(mktemp)
touch -d "@1735689640" "$ref_exact"
touch -d "@1735689639" "$ref_before"
echo "[system] Committing $path"
find "$path" -xdev \
  \( \
    -path /dev \
    -o -path /proc \
    -o -path /sys \
    -o -path /run \
    -o -path /tmp \
  \) -prune \
  -o ! \( \
    -newer "$ref_before" \
    -a ! -newer "$ref_exact" \
  \) \
  -print0 \
| xargs -0 -r -P$(nproc) -n500 touch -h -d "@1735689640"
rm -f "$ref_exact" "$ref_before"
