#!/bin/bash
set -euo pipefail

echo "[system] Committing $path"
path="$(realpath "${1:-/}")"
timestamp=$(TZ=UTC date -d "@946684800" '+%Y%m%d%H%M.00') \
chronic find "$path" -xdev \
  \( \
    -path /dev -o \
    -path /proc -o \
    -path /sys -o \
    -path /run -o \
    -path /tmp \
  \) -prune -o \
  -not \( \
    -ctime "$timestamp" -o \
    -mtime "$timestamp" -o \
    -atime "$timestamp" \
  \) \
  -print0 \
| xargs -0 -r -P$(nproc) -n500 touch -h -t "$timestamp"
