#!/bin/bash
set -e

/usr/lib/system/initialize_pacman
packages=()
aur_packages=()
rm_packages=()
type=packages
for var in "$@"; do
  case "$var" in
  --aur)
    type=aur
    ;;
  --rm)
    type=rm
    ;;
  *)
    case "$type" in
    packages)
      packages+=("$var")
      ;;
    aur)
      aur_packages+=("$var")
      ;;
    rm)
      rm_packages+=("$var")
      ;;
    *)
      echo "Unknown package type: $type"
      exit 1
      ;;
    esac
    ;;
  esac
done

if [ ${#packages[@]} -gt 0 ]; then
  /usr/lib/system/install_packages "${packages[@]}"
fi
if [ ${#aur_packages[@]} -gt 0 ]; then
  /usr/lib/system/install_aur_packages "${aur_packages[@]}"
fi
if [ ${#rm_packages[@]} -gt 0 ]; then
  /usr/lib/system/remove_packages "${rm_packages[@]}"
fi
/usr/lib/system/remove_pacman_files
