#!/bin/bash
set -e
echo "[system] Unmounting /etc bind mounts"
grep -E '[[:space:]]/etc(/|$)' /proc/mounts | awk '{print $2}' | sort -r | xargs -r umount -l
mv /etc /usr
ln -s /usr/etc /etc
echo "[system] Configuring pacman"
echo "DBPath = /usr/lib/pacman" >/etc/pacman.d/ostree.config.conf
echo "IgnoreGroup = modified" >>/etc/pacman.d/ostree.config.conf
mv /var/lib/pacman /usr/lib
echo "[system] Setting up ostree"
mkdir /sysroot
ln -s /sysroot/ostree ostree
