name: Update the pacman cache
description: Update the pacman cache
inputs:
  key:
    description: Cache key
    required: true
  path:
    description: Path to cache
    default: /var/cache/pacman
    required: false
  token:
    description: Github token to use to delete the cache
    default: ${{ github.token }}
    required: false
runs:
  using: composite
  steps:
    - name: Remove old cache
      shell: bash
      continue-on-error: true
      run: |
        git config --global --add safe.directory "$(realpath .)"
        gh cache delete \
          "${{ inputs.key }}" \
          --repo "${{ github.repository }}"
      env:
        GH_TOKEN: ${{ inputs.token }}

    - uses: actions/cache/save@v4
      with:
        path: ${{ inputs.path }}
        key: ${{ inputs.key }}
