# x-name=niricfg

FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN <<EOT
    set -e
    apt-get update
    apt-get install -y --no-install-recommends \
        curl \
        git \
        unzip \
        xz-utils \
        zip \
        libglu1-mesa \
        clang \
        cmake \
        ninja-build \
        pkg-config \
        libgtk-3-dev \
        liblzma-dev \
        libstdc++-12-dev \
        libgstreamer1.0-dev \
        libgstreamer-plugins-base1.0-dev \
        mpv \
        python3-pip \
        pipx
    pipx install flet
    apt-get clean
    rm -rf /var/lib/apt/lists/*
    git config --global --add safe.directory /root/flutter
EOT

ENV PATH="/root/.local/bin:${PATH}"

RUN  flet doctor
