name: niricfg
description: Niri Configuration Generator
version: 0.0.1
publish: null

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flet: ^0.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
