#!/bin/bash
set -eo pipefail

systemctl --failed --no-legend --no-pager |
    while read -r unit _; do
        if [ -n "$unit" ]; then
            echo "--- $unit ---"
            systemctl status "$unit" --no-pager --no-legend || true
        fi
    done

systemctl is-system-running >/dev/null 2>&1
