#!/bin/bash
set -euo pipefail

if chronic systemctl is-system-running --wait; then
  exit 0
fi

systemctl --failed --no-legend --no-pager --plain |
  while read -r unit _; do
    if [ -n "$unit" ]; then
      echo "--- $unit ---"
      systemctl status "$unit" --no-pager --no-legend || true
    fi
  done
exit 1
