import sys
import difflib

from argparse import ArgumentParser
from collections.abc import Iterable
from argparse import Namespace
from pathlib import Path
from typing import Any
from typing import cast

from .config import parse_all_config

kwds: dict[str, str] = {
    "help": "Generate and update variants diagram for documentation",
}

START_COMMENT = """..
  START-VARIANTS-DIAGRAM
  This diagram is automatically generated by `./make.py variants-diagram --update`
  DO NOT EDIT MANUALLY - Changes will be overwritten
  To modify the diagram, edit the variant configuration and run the update command"""

END_COMMENT = """..
  END-VARIANTS-DIAGRAM"""


def register(parser: ArgumentParser) -> None:
    _ = parser.add_argument(
        "--update",
        action="store_true",
        help="Update web/src/variants.rst file with generated diagram",
    )
    _ = parser.add_argument(
        "--check",
        action="store_true",
        help="Check if diagram differs from existing in web/src/variants.rst (exit 2 if different)",
    )


def generate_graphviz_diagram() -> str:
    """Generate graphviz diagram from variant configuration."""
    config = parse_all_config()
    variants_data = config["variants"]

    # Build complete variant list including template variants
    all_variants: dict[str, dict[str, str | list[str] | bool | None]] = {}

    # Add base variants
    for variant_key, variant_info in variants_data.items():
        # Get templates list explicitly
        templates_field = variant_info.get("templates")
        if not isinstance(templates_field, list):
            templates_list = []
        else:
            templates_list = templates_field

        all_variants[variant_key] = {
            "depends": cast(str | None, variant_info.get("depends")),
            "templates": templates_list,
            "is_template_variant": False,
        }

        # Generate template variants
        for tmpl in templates_list:
            template_variant_name = f"{variant_key}-{tmpl}"
            all_variants[template_variant_name] = {
                "depends": variant_key,
                "templates": [tmpl],
                "is_template_variant": True,
            }

    # Add rootfs manually (it's not in variants config)
    all_variants["rootfs"] = {
        "depends": None,
        "templates": [],
        "is_template_variant": False,
    }

    # Generate graphviz dot content
    dot_lines = [
        "digraph variant_hierarchy {",
        "    rankdir=LR;",
        "    bgcolor=transparent;",
        "    node [shape=box,style=filled,fillcolor=white];",
        '    edge [color="#999999",fontcolor="#999999"];',
        "",
    ]

    # Add nodes in sorted order for deterministic output
    for variant_name in sorted(all_variants.keys()):
        # Replace hyphens with underscores for valid graphviz node names
        node_name = variant_name.replace("-", "_")
        dot_lines.append(f'    {node_name} [label="{variant_name}"];')

    dot_lines.append("")

    # Add edges (dependencies) in sorted order for deterministic output
    for variant_name in sorted(all_variants.keys()):
        variant_data = all_variants[variant_name]
        depends = cast(str | None, variant_data["depends"])
        if depends:
            from_node = depends.replace("-", "_")
            to_node = variant_name.replace("-", "_")
            dot_lines.append(f"    {from_node} -> {to_node};")

    dot_lines.append("}")

    # Generate complete content with graphviz directive
    complete_lines = [
        "",
        "",
        ".. graphviz::",
        "",
    ]

    # Add indented diagram content
    for line in dot_lines:
        complete_lines.append("   " + line if line.strip() else "")

    return "\n".join(complete_lines + [""]) + "\n"


def update_variants_rst() -> None:
    """Update web/src/variants.rst file with generated diagram."""
    rst_path = Path("web/src/variants.rst")

    # Read current file
    with open(rst_path, "r") as f:
        content = f.read()

    # Check if markers exist
    if START_COMMENT not in content or END_COMMENT not in content:
        raise ValueError("Markers are missing from variants.rst")

    # Generate new diagram (already includes graphviz directive and proper indentation)
    new_diagram = generate_graphviz_diagram()

    # Build the complete replacement content
    replacement = f"""{START_COMMENT}{new_diagram}{END_COMMENT}"""

    # Replace existing marked content
    start_marker_idx = content.find(START_COMMENT)
    end_marker_idx = content.find(END_COMMENT) + len(END_COMMENT)

    # Find what comes after the end marker to preserve spacing
    after_end = content[end_marker_idx:]

    # Build new content with proper spacing
    new_content = content[:start_marker_idx] + replacement + after_end
    # Write back to file
    with open(rst_path, "w") as f:
        _ = f.write(new_content)


def check_diagram_diff() -> bool | Iterable[str]:
    """Check if generated diagram differs from existing one."""
    rst_path = Path("web/src/variants.rst")

    if not rst_path.exists():
        return True  # Different because file doesn't exist

    # Read current file
    with open(rst_path, "r") as f:
        content = f.read()

    # Check if markers exist
    if START_COMMENT not in content or END_COMMENT not in content:
        raise ValueError("Markers are missing from variants.rst")

    # Extract complete content between markers
    start_idx = content.find(START_COMMENT)

    # Extract just the diagram part (everything between the comment blocks)
    start_marker_end = start_idx + len(START_COMMENT)
    end_marker_start = content.find(END_COMMENT)
    existing_diagram = content[start_marker_end:end_marker_start]
    new_diagram = generate_graphviz_diagram()

    if existing_diagram == new_diagram:
        return False  # Same content

    existing_lines = existing_diagram.splitlines(keepends=True)
    new_lines = new_diagram.splitlines(keepends=True)

    return difflib.unified_diff(
        existing_lines,
        new_lines,
        fromfile="existing",
        tofile="generated",
    )


def command(args: Namespace) -> None:
    update = getattr(args, "update", False)
    check = getattr(args, "check", False)
    if update:
        update_variants_rst()

    if check:
        diff_result = check_diagram_diff()
        if diff_result:
            if not isinstance(diff_result, bool):  # We have actual diff content
                print(
                    "[variants-diagram] Diagram differs from existing:", file=sys.stderr
                )
                _ = sys.stderr.writelines(diff_result)
            sys.exit(2)
        else:
            sys.exit(0)

    if not update and not check:
        print(generate_graphviz_diagram())


if __name__ == "__main__":
    kwds["description"] = kwds["help"]
    del kwds["help"]
    parser = ArgumentParser(
        **cast(  # pyright: ignore[reportAny]
            dict[str, Any],  # pyright: ignore[reportExplicitAny]
            kwds,
        ),
    )
    register(parser)
    args = parser.parse_args()
    command(args)
