import sys
from argparse import ArgumentParser
from argparse import Namespace
from pathlib import Path
from typing import Any
from typing import cast

from .config import parse_all_config

kwds: dict[str, str] = {
    "help": "Generate and update variants diagram for documentation",
}


def register(parser: ArgumentParser):
    parser.add_argument(
        "--update",
        action="store_true",
        help="Update web/src/variants.rst file with generated diagram",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check if diagram differs from existing in web/src/variants.rst (exit 2 if different)",
    )


def generate_graphviz_diagram():
    """Generate graphviz diagram from variant configuration."""
    config = parse_all_config()
    variants_data = config["variants"]

    # Build complete variant list including template variants
    all_variants = {}

    # Add base variants
    for variant_key, variant_info in variants_data.items():
        # Get templates list explicitly
        templates_field = variant_info.get("templates")
        if not isinstance(templates_field, list):
            templates_list = []
        else:
            templates_list = templates_field

        all_variants[variant_key] = {
            "depends": variant_info.get("depends"),
            "templates": templates_list,
            "is_template_variant": False,
        }

        # Generate template variants
        for tmpl in templates_list:
            template_variant_name = f"{variant_key}-{tmpl}"
            all_variants[template_variant_name] = {
                "depends": variant_key,
                "templates": [tmpl],
                "is_template_variant": True,
            }

    # Add rootfs manually (it's not in variants config)
    all_variants["rootfs"] = {
        "depends": None,
        "templates": [],
        "is_template_variant": False,
    }

    # Generate graphviz dot content
    dot_lines = [
        "digraph variant_hierarchy {",
        "    rankdir=LR;",
        "    bgcolor=transparent;",
        "    node [shape=box,style=filled,fillcolor=white];",
        '    edge [color="#999999",fontcolor="#999999"];',
        "",
    ]

    # Add nodes
    for variant_name, variant_data in all_variants.items():
        # Replace hyphens with underscores for valid graphviz node names
        node_name = variant_name.replace("-", "_")
        dot_lines.append(f'    {node_name} [label="{variant_name}"];')

    dot_lines.append("")

    # Add edges (dependencies)
    for variant_name, variant_data in all_variants.items():
        if variant_data["depends"]:
            from_node = variant_data["depends"].replace("-", "_")
            to_node = variant_name.replace("-", "_")
            dot_lines.append(f"    {from_node} -> {to_node};")

    dot_lines.append("}")

    # Generate complete content with graphviz directive
    complete_lines = [
        ".. graphviz::",
        "",
    ]

    # Add indented diagram content
    for line in dot_lines:
        complete_lines.append("   " + line if line.strip() else "")

    return "\n".join(complete_lines) + "\n"


def update_variants_rst():
    """Update web/src/variants.rst file with generated diagram."""
    rst_path = Path("web/src/variants.rst")

    # Read current file
    with open(rst_path, "r") as f:
        content = f.read()

    # Define the comment markers with documentation
    start_comment = """..
  START-VARIANTS-DIAGRAM
  This diagram is automatically generated by `./make.py variants-diagram --update`
  DO NOT EDIT MANUALLY - Changes will be overwritten
  To modify the diagram, edit the variant configuration and run the update command"""

    end_comment = """..
  END-VARIANTS-DIAGRAM"""

    # Check if markers exist
    if start_comment in content and end_comment in content:
        # Extract content between markers
        start_idx = content.find(start_comment)
        end_idx = content.find(end_comment)

    else:
        # Markers don't exist, find existing graphviz content
        lines = content.split("\n")
        start_idx = -1
        end_idx = -1

        for i, line in enumerate(lines):
            if line.strip() == ".. graphviz::":
                start_idx = i
            elif (
                start_idx != -1
                and line.strip()
                and not line.startswith("   ")
                and not line.startswith("\t")
            ):
                end_idx = i
                break

        if start_idx == -1:
            raise ValueError("Could not find graphviz section in web/src/variants.rst")

        if end_idx == -1:
            end_idx = len(lines)

    # Generate new diagram (already includes graphviz directive and proper indentation)
    new_diagram = generate_graphviz_diagram().strip()

    # Build the complete replacement content
    replacement = f"""{start_comment}

{new_diagram}

{end_comment}"""

    # Replace or add the content
    if start_comment in content and end_comment in content:
        # Replace existing marked content
        start_marker_idx = content.find(start_comment)
        end_marker_idx = content.find(end_comment) + len(end_comment)

        # Find what comes after the end marker to preserve spacing
        after_end = content[end_marker_idx:]

        # Build new content with proper spacing
        new_content = content[:start_marker_idx] + replacement + after_end
    else:
        # Add markers around existing content
        lines = content.split("\n")
        start_idx = -1
        end_idx = -1

        for i, line in enumerate(lines):
            if line.strip() == ".. graphviz::":
                start_idx = i
            elif (
                start_idx != -1
                and line.strip()
                and not line.startswith("   ")
                and not line.startswith("\t")
            ):
                end_idx = i
                break

        if start_idx == -1:
            raise ValueError("Could not find graphviz section in web/src/variants.rst")

        if end_idx == -1:
            end_idx = len(lines)

        # Build new content with markers
        before = lines[: start_idx + 2]  # Keep ".. graphviz::" and blank line
        after = lines[end_idx:]

        new_lines = before + [replacement] + after
        new_content = "\n".join(new_lines)

    # Write back to file
    with open(rst_path, "w") as f:
        f.write(new_content)


def check_diagram_diff():
    """Check if generated diagram differs from existing one. Returns False if same, True if different, or diff string."""
    rst_path = Path("web/src/variants.rst")

    if not rst_path.exists():
        return True  # Different because file doesn't exist

    # Read current file
    with open(rst_path, "r") as f:
        content = f.read()

    # Define the comment markers
    start_comment = """..
  START-VARIANTS-DIAGRAM
  This diagram is automatically generated by `./make.py variants-diagram --update`
  DO NOT EDIT MANUALLY - Changes will be overwritten
  To modify the diagram, edit the variant configuration and run the update command"""

    end_comment = """..
  END-VARIANTS-DIAGRAM"""

    # Check if markers exist
    if start_comment in content and end_comment in content:
        # Extract complete content between markers
        start_idx = content.find(start_comment)

        # Extract just the diagram part (everything between the comment blocks)
        start_marker_end = start_idx + len(start_comment)
        end_marker_start = content.find(end_comment)
        existing_diagram = content[start_marker_end:end_marker_start].strip()

    else:
        # Markers don't exist, use legacy parsing
        lines = content.split("\n")
        start_idx = -1
        end_idx = -1

        for i, line in enumerate(lines):
            if line.strip() == ".. graphviz::":
                start_idx = i
            elif (
                start_idx != -1
                and line.strip()
                and not line.startswith("   ")
                and not line.startswith("\t")
            ):
                end_idx = i
                break

        if start_idx == -1:
            return True  # Different because no graphviz section found

        if end_idx == -1:
            end_idx = len(lines)

        # Extract existing diagram (skip ".. graphviz::" and blank line)
        if start_idx + 2 < end_idx:
            existing_lines = lines[start_idx + 2 : end_idx]
            # Remove the 3-space indentation from each line
            existing_diagram = "".join(
                line[3:] if line.startswith("   ") else line for line in existing_lines
            ).strip()
        else:
            existing_diagram = ""

    new_diagram = generate_graphviz_diagram().strip()

    if existing_diagram == new_diagram:
        return False  # Same content

    # Generate diff for debugging
    import difflib

    existing_lines = existing_diagram.splitlines(keepends=True)
    new_lines = new_diagram.splitlines(keepends=True)

    diff = difflib.unified_diff(
        existing_lines, new_lines, fromfile="existing", tofile="generated", lineterm=""
    )

    diff_output = "".join(diff)
    if not diff_output:
        return True  # Different but no diff (edge case)

    return diff_output


def command(args: Namespace):
    if args.check:
        diff_result = check_diagram_diff()
        if diff_result:
            if not isinstance(diff_result, bool):  # We have actual diff content
                print(
                    "[variants-diagram] Diagram differs from existing:", file=sys.stderr
                )
                print(diff_result, file=sys.stderr)
            sys.exit(2)
        else:
            sys.exit(0)
    elif args.update:
        update_variants_rst()
    else:
        # Default: output to stdout
        print(generate_graphviz_diagram())


if __name__ == "__main__":
    kwds["description"] = kwds["help"]
    del kwds["help"]
    parser = ArgumentParser(
        **cast(  # pyright: ignore[reportAny]
            dict[str, Any],  # pyright: ignore[reportExplicitAny]
            kwds,
        ),
    )
    register(parser)
    args = parser.parse_args()
    command(args)
