#########################################
# THIS FILE IS DYNAMICALLY GENERATED    #
# Run the following to update the file: #
#   $ ./make.py workflow                #
#########################################
name: Build images
on:
  pull_request: &on-filter
    branches:
      - master
    paths:
      - .github/workflows/tool-builder.yaml
      - .github/workflows/tool-niricfg.yaml
      - .github/workflows/tool-iso-runner.yaml
      - .github/workflows/build.yaml
      - .github/workflows/build-variant.yaml
      - .github/workflows/iso.yaml
      - .github/workflows/manifest.yaml
      - .github/workflows/push-variant.yaml
      - .github/workflows/scan.yaml
      - ".github/actions/**"
      - "tools/dockerfile2llbjson/**"
      - "tools/builder/**"
      - "tools/iso-runner/**"
      - "tools/niricfg/**"
      - "make/__main__.py"
      - "make/__init__.py"
      - "make/iso.py"
      - "make/scan.py"
      - "make/pull.py"
      - "make/push.py"
      - "make/build.py"
      - "make/builder.py"
      - "make/checkupdates.py"
      - "make/hash.py"
      - "make/rootfs.py"
      - "make/iso-runner.py"
      - "make/hash-builder.py"
      - "make/hash-iso-runner.py"
      - "make/hash-niricfg.py"
      - "make/niricfg.py"
      - "make/manifest.py"
      - "make/check.py"
      - "make/ref.py"
      - "make/test.py"
      - "make/boot.py"
      - "make/shell.py"
      - "make/variants.py"
      - "make/workflow.py"
      - "overlay/**"
      - "templates/**"
      - "variants/**"
      - rootfs.Containerfile
      - variant.Containerfile
      - make.py
      - seccomp.json
      - .containerignore
  push: *on-filter
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  ######################################
  #               UNIQUE               #
  ######################################

  notifications:
    if: github.repository == 'Eeems/arkes' && github.actor != 'dependabot[bot]'
    name: Clear notifications
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
      - name: Clean cancellation notifications
        uses: ./.github/actions/clean-cancelled-notifications
        with:
          pat: ${{ secrets.NOTIFICATION_PAT }}

  builder:
    name: Build builder image
    uses: ./.github/workflows/tool-builder.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  tool-niricfg:
    name: Build niricfg application
    uses: ./.github/workflows/tool-niricfg.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  tool-iso-runner:
    name: Build iso runner image
    needs: builder
    uses: ./.github/workflows/tool-iso-runner.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      builder: ${{ needs.builder.outputs.unique_tag }}

  check:
    name: Ensure config is valid
    runs-on: ubuntu-latest
    needs: builder
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/eeems/arkes-builder:${{ needs.builder.outputs.unique_tag }}
      options: >-
        --privileged
        --security-opt seccomp=unconfined
        --security-opt apparmor=unconfined
        --cap-add=SYS_ADMIN
        --cap-add=NET_ADMIN
        --device /dev/fuse
        --tmpfs /tmp
        --tmpfs /run
        --userns=host
        --volume=/:/run/host
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
      - name: Cache venv
        uses: actions/cache@v5
        with:
          path: .venv
          key: venv-${{ needs.builder.outputs.unique_tag }}-${{ hashFiles('make/check.py') }}
      - name: Cache go
        uses: actions/cache@v5
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ hashFiles('**/go.mod') }}-${{ hashFiles('**/go.sum') }}
      - name: Ensure config is valid
        shell: bash
        run: ./make.py check
        env:
          TMPDIR: ${{ runner.temp }}

  manifest:
    name: Generate manifest
    if: "!cancelled()"
    needs:
      - builder
      - push_atomic
      - push_atomic-nvidia
      - push_base
      - push_base-rolling
      - push_base-slim
      - push_cosmic
      - push_eeems
      - push_eeems-framework
      - push_eeems-nvidia
      - push_eeems-system76
      - push_gnome
      - push_graphical
      - push_kde
      - push_rootfs
    uses: ./.github/workflows/manifest.yaml
    secrets: inherit
    permissions: &permissions
      contents: write
      actions: write
      packages: write
      security-events: write
    with:
      cache: false
      builder: ${{ needs.builder.outputs.unique_tag }}

  ######################################
  #                BUILD               #
  ######################################

  rootfs:
    name: Build eeems/arkes:rootfs image
    needs:
      - builder
      - check
    uses: ./.github/workflows/build-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: rootfs
      builder: ${{ needs.builder.outputs.unique_tag }}

  base:
    name: Build eeems/arkes:base image
    needs:
      - builder
      - rootfs
    uses: ./.github/workflows/build-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: base
      builder: ${{ needs.builder.outputs.unique_tag }}
      updates: ${{ fromJson(needs['rootfs'].outputs.updates) }}
      artifact: rootfs
      digest: ${{ needs['rootfs'].outputs.digest }}

  base-rolling:
    name: Build eeems/arkes:base-rolling image
    needs:
      - builder
      - base
    uses: ./.github/workflows/build-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: base-rolling
      builder: ${{ needs.builder.outputs.unique_tag }}
      updates: ${{ fromJson(needs['base'].outputs.updates) }}
      artifact: base
      digest: ${{ needs['base'].outputs.digest }}

  base-slim:
    name: Build eeems/arkes:base-slim image
    needs:
      - builder
      - base
    uses: ./.github/workflows/build-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: base-slim
      builder: ${{ needs.builder.outputs.unique_tag }}
      updates: ${{ fromJson(needs['base'].outputs.updates) }}
      artifact: base
      digest: ${{ needs['base'].outputs.digest }}

  graphical:
    name: Build eeems/arkes:graphical image
    needs:
      - builder
      - base
    uses: ./.github/workflows/build-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: graphical
      builder: ${{ needs.builder.outputs.unique_tag }}
      updates: ${{ fromJson(needs['base'].outputs.updates) }}
      artifact: base
      digest: ${{ needs['base'].outputs.digest }}

  atomic:
    name: Build eeems/arkes:atomic image
    needs:
      - builder
      - graphical
    uses: ./.github/workflows/build-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: atomic
      builder: ${{ needs.builder.outputs.unique_tag }}
      updates: ${{ fromJson(needs['graphical'].outputs.updates) }}
      artifact: graphical
      digest: ${{ needs['graphical'].outputs.digest }}

  atomic-nvidia:
    name: Build eeems/arkes:atomic-nvidia image
    needs:
      - builder
      - atomic
    uses: ./.github/workflows/build-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: atomic-nvidia
      builder: ${{ needs.builder.outputs.unique_tag }}
      updates: ${{ fromJson(needs['atomic'].outputs.updates) }}
      artifact: atomic
      digest: ${{ needs['atomic'].outputs.digest }}

  cosmic:
    name: Build eeems/arkes:cosmic image
    needs:
      - builder
      - graphical
    uses: ./.github/workflows/build-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: cosmic
      builder: ${{ needs.builder.outputs.unique_tag }}
      updates: ${{ fromJson(needs['graphical'].outputs.updates) }}
      artifact: graphical
      digest: ${{ needs['graphical'].outputs.digest }}

  eeems:
    name: Build eeems/arkes:eeems image
    needs:
      - builder
      - atomic
    uses: ./.github/workflows/build-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: eeems
      builder: ${{ needs.builder.outputs.unique_tag }}
      updates: ${{ fromJson(needs['atomic'].outputs.updates) }}
      artifact: atomic
      digest: ${{ needs['atomic'].outputs.digest }}
      cleanup: true

  eeems-framework:
    name: Build eeems/arkes:eeems-framework image
    needs:
      - builder
      - eeems
    uses: ./.github/workflows/build-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: eeems-framework
      builder: ${{ needs.builder.outputs.unique_tag }}
      updates: ${{ fromJson(needs['eeems'].outputs.updates) }}
      artifact: eeems
      digest: ${{ needs['eeems'].outputs.digest }}
      cleanup: true

  eeems-nvidia:
    name: Build eeems/arkes:eeems-nvidia image
    needs:
      - builder
      - eeems
    uses: ./.github/workflows/build-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: eeems-nvidia
      builder: ${{ needs.builder.outputs.unique_tag }}
      updates: ${{ fromJson(needs['eeems'].outputs.updates) }}
      artifact: eeems
      digest: ${{ needs['eeems'].outputs.digest }}
      cleanup: true

  eeems-system76:
    name: Build eeems/arkes:eeems-system76 image
    needs:
      - builder
      - eeems
    uses: ./.github/workflows/build-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: eeems-system76
      builder: ${{ needs.builder.outputs.unique_tag }}
      updates: ${{ fromJson(needs['eeems'].outputs.updates) }}
      artifact: eeems
      digest: ${{ needs['eeems'].outputs.digest }}
      cleanup: true

  gnome:
    name: Build eeems/arkes:gnome image
    needs:
      - builder
      - graphical
    uses: ./.github/workflows/build-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: gnome
      builder: ${{ needs.builder.outputs.unique_tag }}
      updates: ${{ fromJson(needs['graphical'].outputs.updates) }}
      artifact: graphical
      digest: ${{ needs['graphical'].outputs.digest }}

  kde:
    name: Build eeems/arkes:kde image
    needs:
      - builder
      - graphical
    uses: ./.github/workflows/build-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: kde
      builder: ${{ needs.builder.outputs.unique_tag }}
      updates: ${{ fromJson(needs['graphical'].outputs.updates) }}
      artifact: graphical
      digest: ${{ needs['graphical'].outputs.digest }}

  ######################################
  #                SCAN                #
  ######################################

  scan_rootfs:
    name: Scan image for rootfs
    if: github.event_name != 'pull_request' || fromJson(needs['rootfs'].outputs.updates)
    needs:
      - builder
      - rootfs
    uses: ./.github/workflows/scan.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: rootfs
      push: ${{ github.event_name != 'pull_request' }}
      artifact: ${{ fromJson(needs['rootfs'].outputs.updates) && 'rootfs' || '' }}
      digest: ${{ needs['rootfs'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  scan_base:
    name: Scan image for base
    if: github.event_name != 'pull_request' || fromJson(needs['base'].outputs.updates)
    needs:
      - builder
      - base
    uses: ./.github/workflows/scan.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: base
      push: ${{ github.event_name != 'pull_request' }}
      artifact: ${{ fromJson(needs['base'].outputs.updates) && 'base' || '' }}
      digest: ${{ needs['base'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  scan_base-rolling:
    name: Scan image for base-rolling
    if: github.event_name != 'pull_request' || fromJson(needs['base-rolling'].outputs.updates)
    needs:
      - builder
      - base-rolling
    uses: ./.github/workflows/scan.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: base-rolling
      push: ${{ github.event_name != 'pull_request' }}
      artifact: ${{ fromJson(needs['base-rolling'].outputs.updates) && 'base-rolling' || '' }}
      digest: ${{ needs['base-rolling'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  scan_base-slim:
    name: Scan image for base-slim
    if: github.event_name != 'pull_request' || fromJson(needs['base-slim'].outputs.updates)
    needs:
      - builder
      - base-slim
    uses: ./.github/workflows/scan.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: base-slim
      push: ${{ github.event_name != 'pull_request' }}
      artifact: ${{ fromJson(needs['base-slim'].outputs.updates) && 'base-slim' || '' }}
      digest: ${{ needs['base-slim'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  scan_graphical:
    name: Scan image for graphical
    if: github.event_name != 'pull_request' || fromJson(needs['graphical'].outputs.updates)
    needs:
      - builder
      - graphical
    uses: ./.github/workflows/scan.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: graphical
      push: ${{ github.event_name != 'pull_request' }}
      artifact: ${{ fromJson(needs['graphical'].outputs.updates) && 'graphical' || '' }}
      digest: ${{ needs['graphical'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  scan_atomic:
    name: Scan image for atomic
    if: github.event_name != 'pull_request' || fromJson(needs['atomic'].outputs.updates)
    needs:
      - builder
      - atomic
    uses: ./.github/workflows/scan.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: atomic
      push: ${{ github.event_name != 'pull_request' }}
      artifact: ${{ fromJson(needs['atomic'].outputs.updates) && 'atomic' || '' }}
      digest: ${{ needs['atomic'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  scan_atomic-nvidia:
    name: Scan image for atomic-nvidia
    if: github.event_name != 'pull_request' || fromJson(needs['atomic-nvidia'].outputs.updates)
    needs:
      - builder
      - atomic-nvidia
    uses: ./.github/workflows/scan.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: atomic-nvidia
      push: ${{ github.event_name != 'pull_request' }}
      artifact: ${{ fromJson(needs['atomic-nvidia'].outputs.updates) && 'atomic-nvidia' || '' }}
      digest: ${{ needs['atomic-nvidia'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  scan_cosmic:
    name: Scan image for cosmic
    if: github.event_name != 'pull_request' || fromJson(needs['cosmic'].outputs.updates)
    needs:
      - builder
      - cosmic
    uses: ./.github/workflows/scan.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: cosmic
      push: ${{ github.event_name != 'pull_request' }}
      artifact: ${{ fromJson(needs['cosmic'].outputs.updates) && 'cosmic' || '' }}
      digest: ${{ needs['cosmic'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  scan_eeems:
    name: Scan image for eeems
    if: github.event_name != 'pull_request' || fromJson(needs['eeems'].outputs.updates)
    needs:
      - builder
      - eeems
    uses: ./.github/workflows/scan.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: eeems
      push: ${{ github.event_name != 'pull_request' }}
      artifact: ${{ fromJson(needs['eeems'].outputs.updates) && 'eeems' || '' }}
      digest: ${{ needs['eeems'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  scan_eeems-framework:
    name: Scan image for eeems-framework
    if: github.event_name != 'pull_request' || fromJson(needs['eeems-framework'].outputs.updates)
    needs:
      - builder
      - eeems-framework
    uses: ./.github/workflows/scan.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: eeems-framework
      push: ${{ github.event_name != 'pull_request' }}
      artifact: ${{ fromJson(needs['eeems-framework'].outputs.updates) && 'eeems-framework' || '' }}
      digest: ${{ needs['eeems-framework'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  scan_eeems-nvidia:
    name: Scan image for eeems-nvidia
    if: github.event_name != 'pull_request' || fromJson(needs['eeems-nvidia'].outputs.updates)
    needs:
      - builder
      - eeems-nvidia
    uses: ./.github/workflows/scan.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: eeems-nvidia
      push: ${{ github.event_name != 'pull_request' }}
      artifact: ${{ fromJson(needs['eeems-nvidia'].outputs.updates) && 'eeems-nvidia' || '' }}
      digest: ${{ needs['eeems-nvidia'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  scan_eeems-system76:
    name: Scan image for eeems-system76
    if: github.event_name != 'pull_request' || fromJson(needs['eeems-system76'].outputs.updates)
    needs:
      - builder
      - eeems-system76
    uses: ./.github/workflows/scan.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: eeems-system76
      push: ${{ github.event_name != 'pull_request' }}
      artifact: ${{ fromJson(needs['eeems-system76'].outputs.updates) && 'eeems-system76' || '' }}
      digest: ${{ needs['eeems-system76'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  scan_gnome:
    name: Scan image for gnome
    if: github.event_name != 'pull_request' || fromJson(needs['gnome'].outputs.updates)
    needs:
      - builder
      - gnome
    uses: ./.github/workflows/scan.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: gnome
      push: ${{ github.event_name != 'pull_request' }}
      artifact: ${{ fromJson(needs['gnome'].outputs.updates) && 'gnome' || '' }}
      digest: ${{ needs['gnome'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  scan_kde:
    name: Scan image for kde
    if: github.event_name != 'pull_request' || fromJson(needs['kde'].outputs.updates)
    needs:
      - builder
      - kde
    uses: ./.github/workflows/scan.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: kde
      push: ${{ github.event_name != 'pull_request' }}
      artifact: ${{ fromJson(needs['kde'].outputs.updates) && 'kde' || '' }}
      digest: ${{ needs['kde'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  ######################################
  #                 ISO                #
  ######################################

  iso_base:
    name: Generate iso for base
    needs:
      - builder
      - tool-iso-runner
      - base
    uses: ./.github/workflows/iso.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: base
      artifact: base
      digest: ${{ needs['base'].outputs.digest }}
      pull: ${{ github.event_name != 'pull_request' && fromJson(needs['base'].outputs.updates) }}
      push: ${{ github.event_name != 'pull_request' }}
      builder: ${{ needs.builder.outputs.unique_tag }}
      iso_runner: ${{ needs.tool-iso-runner.outputs.hash }}


  iso_base-slim:
    name: Generate iso for base-slim
    needs:
      - builder
      - tool-iso-runner
      - base-slim
    uses: ./.github/workflows/iso.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: base-slim
      artifact: base-slim
      digest: ${{ needs['base-slim'].outputs.digest }}
      pull: ${{ github.event_name != 'pull_request' && fromJson(needs['base-slim'].outputs.updates) }}
      push: ${{ github.event_name != 'pull_request' }}
      builder: ${{ needs.builder.outputs.unique_tag }}
      iso_runner: ${{ needs.tool-iso-runner.outputs.hash }}

  iso_graphical:
    name: Generate iso for graphical
    needs:
      - builder
      - tool-iso-runner
      - graphical
    uses: ./.github/workflows/iso.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: graphical
      artifact: graphical
      digest: ${{ needs['graphical'].outputs.digest }}
      pull: ${{ github.event_name != 'pull_request' && fromJson(needs['graphical'].outputs.updates) }}
      push: ${{ github.event_name != 'pull_request' }}
      builder: ${{ needs.builder.outputs.unique_tag }}
      iso_runner: ${{ needs.tool-iso-runner.outputs.hash }}

  iso_atomic:
    name: Generate iso for atomic
    needs:
      - builder
      - tool-iso-runner
      - atomic
    uses: ./.github/workflows/iso.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: atomic
      artifact: atomic
      digest: ${{ needs['atomic'].outputs.digest }}
      pull: ${{ github.event_name != 'pull_request' && fromJson(needs['atomic'].outputs.updates) }}
      push: ${{ github.event_name != 'pull_request' }}
      builder: ${{ needs.builder.outputs.unique_tag }}
      iso_runner: ${{ needs.tool-iso-runner.outputs.hash }}

  iso_atomic-nvidia:
    name: Generate iso for atomic-nvidia
    needs:
      - builder
      - tool-iso-runner
      - atomic-nvidia
    uses: ./.github/workflows/iso.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: atomic-nvidia
      artifact: atomic-nvidia
      digest: ${{ needs['atomic-nvidia'].outputs.digest }}
      pull: ${{ github.event_name != 'pull_request' && fromJson(needs['atomic-nvidia'].outputs.updates) }}
      push: ${{ github.event_name != 'pull_request' }}
      builder: ${{ needs.builder.outputs.unique_tag }}
      iso_runner: ${{ needs.tool-iso-runner.outputs.hash }}

  iso_cosmic:
    name: Generate iso for cosmic
    needs:
      - builder
      - tool-iso-runner
      - cosmic
    uses: ./.github/workflows/iso.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: cosmic
      artifact: cosmic
      digest: ${{ needs['cosmic'].outputs.digest }}
      pull: ${{ github.event_name != 'pull_request' && fromJson(needs['cosmic'].outputs.updates) }}
      push: ${{ github.event_name != 'pull_request' }}
      builder: ${{ needs.builder.outputs.unique_tag }}
      iso_runner: ${{ needs.tool-iso-runner.outputs.hash }}

  iso_eeems:
    name: Generate iso for eeems
    needs:
      - builder
      - tool-iso-runner
      - eeems
    uses: ./.github/workflows/iso.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: eeems
      artifact: eeems
      digest: ${{ needs['eeems'].outputs.digest }}
      pull: ${{ github.event_name != 'pull_request' && fromJson(needs['eeems'].outputs.updates) }}
      push: ${{ github.event_name != 'pull_request' }}
      builder: ${{ needs.builder.outputs.unique_tag }}
      iso_runner: ${{ needs.tool-iso-runner.outputs.hash }}

  iso_eeems-framework:
    name: Generate iso for eeems-framework
    needs:
      - builder
      - tool-iso-runner
      - eeems-framework
    uses: ./.github/workflows/iso.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: eeems-framework
      artifact: eeems-framework
      digest: ${{ needs['eeems-framework'].outputs.digest }}
      pull: ${{ github.event_name != 'pull_request' && fromJson(needs['eeems-framework'].outputs.updates) }}
      push: ${{ github.event_name != 'pull_request' }}
      builder: ${{ needs.builder.outputs.unique_tag }}
      iso_runner: ${{ needs.tool-iso-runner.outputs.hash }}

  iso_eeems-nvidia:
    name: Generate iso for eeems-nvidia
    needs:
      - builder
      - tool-iso-runner
      - eeems-nvidia
    uses: ./.github/workflows/iso.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: eeems-nvidia
      artifact: eeems-nvidia
      digest: ${{ needs['eeems-nvidia'].outputs.digest }}
      pull: ${{ github.event_name != 'pull_request' && fromJson(needs['eeems-nvidia'].outputs.updates) }}
      push: ${{ github.event_name != 'pull_request' }}
      builder: ${{ needs.builder.outputs.unique_tag }}
      iso_runner: ${{ needs.tool-iso-runner.outputs.hash }}

  iso_eeems-system76:
    name: Generate iso for eeems-system76
    needs:
      - builder
      - tool-iso-runner
      - eeems-system76
    uses: ./.github/workflows/iso.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: eeems-system76
      artifact: eeems-system76
      digest: ${{ needs['eeems-system76'].outputs.digest }}
      pull: ${{ github.event_name != 'pull_request' && fromJson(needs['eeems-system76'].outputs.updates) }}
      push: ${{ github.event_name != 'pull_request' }}
      builder: ${{ needs.builder.outputs.unique_tag }}
      iso_runner: ${{ needs.tool-iso-runner.outputs.hash }}

  iso_gnome:
    name: Generate iso for gnome
    needs:
      - builder
      - tool-iso-runner
      - gnome
    uses: ./.github/workflows/iso.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: gnome
      artifact: gnome
      digest: ${{ needs['gnome'].outputs.digest }}
      pull: ${{ github.event_name != 'pull_request' && fromJson(needs['gnome'].outputs.updates) }}
      push: ${{ github.event_name != 'pull_request' }}
      builder: ${{ needs.builder.outputs.unique_tag }}
      iso_runner: ${{ needs.tool-iso-runner.outputs.hash }}

  iso_kde:
    name: Generate iso for kde
    needs:
      - builder
      - tool-iso-runner
      - kde
    uses: ./.github/workflows/iso.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: kde
      artifact: kde
      digest: ${{ needs['kde'].outputs.digest }}
      pull: ${{ github.event_name != 'pull_request' && fromJson(needs['kde'].outputs.updates) }}
      push: ${{ github.event_name != 'pull_request' }}
      builder: ${{ needs.builder.outputs.unique_tag }}
      iso_runner: ${{ needs.tool-iso-runner.outputs.hash }}

  ######################################
  #                PUSH                #
  ######################################

  push_rootfs:
    name: Push eeems/arkes:rootfs image
    if: github.event_name != 'pull_request' && fromJson(needs['rootfs'].outputs.updates)
    needs:
      - builder
      - rootfs
    uses: ./.github/workflows/push-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: rootfs
      digest: ${{ needs['rootfs'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  push_base:
    name: Push eeems/arkes:base image
    if: github.event_name != 'pull_request' && fromJson(needs['base'].outputs.updates)
    needs:
      - builder
      - base
      - iso_base
    uses: ./.github/workflows/push-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: base
      digest: ${{ needs['base'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  push_base-rolling:
    name: Push eeems/arkes:base-rolling image
    if: github.event_name != 'pull_request' && fromJson(needs['base-rolling'].outputs.updates)
    needs:
      - builder
      - base-rolling
    uses: ./.github/workflows/push-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: base-rolling
      digest: ${{ needs['base-rolling'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  push_base-slim:
    name: Push eeems/arkes:base-slim image
    if: github.event_name != 'pull_request' && fromJson(needs['base-slim'].outputs.updates)
    needs:
      - builder
      - base-slim
      - iso_base-slim
    uses: ./.github/workflows/push-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: base-slim
      digest: ${{ needs['base-slim'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  push_graphical:
    name: Push eeems/arkes:graphical image
    if: github.event_name != 'pull_request' && fromJson(needs['graphical'].outputs.updates)
    needs:
      - builder
      - graphical
      - iso_graphical
    uses: ./.github/workflows/push-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: graphical
      digest: ${{ needs['graphical'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  push_atomic:
    name: Push eeems/arkes:atomic image
    if: github.event_name != 'pull_request' && fromJson(needs['atomic'].outputs.updates)
    needs:
      - builder
      - atomic
      - iso_atomic
    uses: ./.github/workflows/push-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: atomic
      digest: ${{ needs['atomic'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  push_atomic-nvidia:
    name: Push eeems/arkes:atomic-nvidia image
    if: github.event_name != 'pull_request' && fromJson(needs['atomic-nvidia'].outputs.updates)
    needs:
      - builder
      - atomic-nvidia
      - iso_atomic-nvidia
    uses: ./.github/workflows/push-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: atomic-nvidia
      digest: ${{ needs['atomic-nvidia'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  push_cosmic:
    name: Push eeems/arkes:cosmic image
    if: github.event_name != 'pull_request' && fromJson(needs['cosmic'].outputs.updates)
    needs:
      - builder
      - cosmic
      - iso_cosmic
    uses: ./.github/workflows/push-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: cosmic
      digest: ${{ needs['cosmic'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  push_eeems:
    name: Push eeems/arkes:eeems image
    if: github.event_name != 'pull_request' && fromJson(needs['eeems'].outputs.updates)
    needs:
      - builder
      - eeems
      - iso_eeems
    uses: ./.github/workflows/push-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: eeems
      digest: ${{ needs['eeems'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  push_eeems-framework:
    name: Push eeems/arkes:eeems-framework image
    if: github.event_name != 'pull_request' && fromJson(needs['eeems-framework'].outputs.updates)
    needs:
      - builder
      - eeems-framework
      - iso_eeems-framework
    uses: ./.github/workflows/push-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: eeems-framework
      digest: ${{ needs['eeems-framework'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  push_eeems-nvidia:
    name: Push eeems/arkes:eeems-nvidia image
    if: github.event_name != 'pull_request' && fromJson(needs['eeems-nvidia'].outputs.updates)
    needs:
      - builder
      - eeems-nvidia
      - iso_eeems-nvidia
    uses: ./.github/workflows/push-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: eeems-nvidia
      digest: ${{ needs['eeems-nvidia'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  push_eeems-system76:
    name: Push eeems/arkes:eeems-system76 image
    if: github.event_name != 'pull_request' && fromJson(needs['eeems-system76'].outputs.updates)
    needs:
      - builder
      - eeems-system76
      - iso_eeems-system76
    uses: ./.github/workflows/push-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: eeems-system76
      digest: ${{ needs['eeems-system76'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  push_gnome:
    name: Push eeems/arkes:gnome image
    if: github.event_name != 'pull_request' && fromJson(needs['gnome'].outputs.updates)
    needs:
      - builder
      - gnome
      - iso_gnome
    uses: ./.github/workflows/push-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: gnome
      digest: ${{ needs['gnome'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}

  push_kde:
    name: Push eeems/arkes:kde image
    if: github.event_name != 'pull_request' && fromJson(needs['kde'].outputs.updates)
    needs:
      - builder
      - kde
      - iso_kde
    uses: ./.github/workflows/push-variant.yaml
    secrets: inherit
    permissions: *permissions
    with:
      variant: kde
      digest: ${{ needs['kde'].outputs.digest }}
      builder: ${{ needs.builder.outputs.unique_tag }}
