name: Build iso runner image
on:
  workflow_call:
    inputs:
      builder:
        description: Builder tag to use
        required: false
        type: string
    outputs:
      hash:
        description: Content hash of the iso runner image
        value: ${{ jobs.iso-runner.outputs.hash }}
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  iso-runner:
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.meta.outputs.hash }}
    container:
      image: ghcr.io/eeems/arkes-builder:${{ inputs.builder || github.head_ref || github.ref_name }}
      options: >-
        --privileged
        --security-opt seccomp=unconfined
        --security-opt apparmor=unconfined
        --cap-add=SYS_ADMIN
        --cap-add=NET_ADMIN
        --device /dev/fuse
        --tmpfs /tmp
        --tmpfs /run
        --userns=host
        --volume=/:/run/host
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup container
        uses: ./.github/actions/setup-container
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Login to ghcr
        uses: docker/login-action@v4
        with:
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Generate tags
        id: meta
        run: |
          pip install pyxattr progressbar2
          IMAGE_NAME=ghcr.io/eeems/arkes-builder
          HASH="$(python ./make/hash-iso-runner.py --no-newline)"
          {
            echo "tags=${IMAGE_NAME}:iso-runner,${IMAGE_NAME}:${HASH}"
            echo "hash=${HASH}"
            echo "missing=$(skopeo list-tags docker://$IMAGE_NAME | jq --arg hash "$HASH" 'any(.Tags[]; . == $hash) | not')"
          } >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

      - name: Build and push
        if: fromJson(steps.meta.outputs.missing)
        uses: ./.github/actions/run-with-podman-service
        with:
          run: |
            ./make.py iso-runner \
              --source-url=${{ github.server_url }}/${{ github.repository }} \
              --revision=${{ github.sha }}
            podman tag \
              ghcr.io/eeems/arkes-builder:iso-runner \
              ghcr.io/eeems/arkes-builder:"$HASH"
            for tag in iso-runner "$HASH"; do
              podman push \
                --retry=5 \
                --compression-format=zstd:chunked \
                ghcr.io/eeems/arkes-builder:${tag}
            done
        env:
          HASH: ${{ steps.meta.outputs.hash }}
